[package]
name = "oxidiviner"
version = "0.1.0"
edition = "2021"
description = "OxiDiviner: Time Series Analysis and Forecasting Library"
license = "MIT"
authors = ["OxiDiviner Team"]
readme = "README.md"
repository = "https://github.com/OxiDiviner/oxdiviner"
homepage = "https://github.com/OxiDiviner/oxdiviner"
documentation = "https://docs.rs/oxidiviner"
keywords = ["time-series", "forecasting", "statistics", "analysis", "data"]
categories = ["science", "mathematics", "algorithms", "finance"]
# Exclude files and directories from being included in the published package
exclude = [
    ".cursor/*",
    "tests/*",
    "examples/*",
    "target/*",
    "Cargo.lock"
]

[dependencies]
chrono = { version = ">=0.4.41", features = ["serde"] }
rand = ">=0.9.1"
statrs = ">=0.18.0"
plotters = { version = ">=0.3.7", optional = true }
polars = { version = ">=0.47.1", optional = true, features = ["lazy", "dtype-full"] }
thiserror = ">=2.0.12"
ndarray = { version = ">=0.16.1", optional = true }
serde = { version = ">=1.0.219", features = ["derive"] }

[features]
default = []
plotting = ["plotters"]
ndarray_support = ["ndarray"]
polars_integration = ["polars"]

[[example]]
name = "ets_demo"
path = "examples/ets_demo.rs"
