[workspace]
members = [
    "oxidiviner-core",
    "oxidiviner-math",
    "oxidiviner-moving-average",
    "oxidiviner-exponential-smoothing",
    "oxidiviner-autoregressive",
    "examples",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["OxiDiviner Team"]
repository = "https://github.com/OxiDiviner/oxdiviner"
homepage = "https://github.com/OxiDiviner/oxdiviner"
documentation = "https://docs.rs/oxidiviner"
keywords = ["time-series", "forecasting", "statistics", "analysis", "data"]
categories = ["science", "mathematics", "algorithms", "finance"]

[workspace.dependencies]
chrono = { version = ">=0.4.41", features = ["serde"] }
rand = ">=0.9.1"
statrs = ">=0.18.0"
plotters = { version = ">=0.3.7" }
polars = { version = ">=0.47.1", features = ["lazy", "dtype-full"] }
thiserror = ">=2.0.12"
ndarray = { version = ">=0.16.1" }
serde = { version = ">=1.0.219", features = ["derive"] }
