# Code Coverage Configuration for OxiDiviner (Single Crate)
# Run with: cargo tarpaulin --config tarpaulin.toml

[report]
# Output formats
out = ["Html", "Lcov", "Json", "Stdout"]

# Output directory for reports
output-dir = "target/coverage"

# Minimum coverage threshold (60% is realistic for the unified crate)
fail-under = 60.0

[run]
# Target the oxidiviner crate
# workspace = false (commented out since we're now single-crate)

# Test all features
all-features = true

# Include doctests in coverage
count-doc-tests = true

# Timeout for tests (10 minutes for comprehensive testing)
timeout = "600s"

# Change working directory to the oxidiviner crate
root = "oxidiviner"

# Exclude files/directories from coverage
exclude = [
    # Test files
    "*/tests/*",
    "*/benches/*",
    
    # Example files (they're demos, not production code)
    "examples/*",
    
    # Generated files
    "target/*",
    
    # Documentation and config files
    "*.md",
    "*.toml",
    "*.txt",
    "*.yml",
    "*.yaml",
    
    # Build scripts
    "build.rs"
]

# Run types
run-types = ["Tests", "Doctests"]

[tool.coverage]
# Line coverage
line = true

# Branch coverage  
branch = true

# Function coverage
region = true

[target.'cfg(not(target_os = "windows"))']
# Additional options for non-Windows systems
engine = "llvm"

[target.'cfg(target_os = "windows")']
# Windows-specific options
engine = "ptrace"

# Advanced coverage options
[advanced]
# Include all source files even if not executed
force-clean = true

# Generate more detailed reports
verbose = true 