[package]
name = "oxidiviner"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository = "https://github.com/rustic-ml/OxiDiviner"
homepage = "https://github.com/rustic-ml/OxiDiviner"
documentation = "https://docs.rs/oxidiviner"
keywords.workspace = true
categories.workspace = true
description = "A comprehensive Rust library for time series analysis and forecasting including moving average, exponential smoothing, autoregressive, and GARCH models"

[dependencies]
oxidiviner-core = { version = "0.3.0", path = "../oxidiviner-core" }
oxidiviner-math = { version = "0.3.0", path = "../oxidiviner-math" }
oxidiviner-moving-average = { version = "0.3.0", path = "../oxidiviner-moving-average" }
oxidiviner-exponential-smoothing = { version = "0.3.0", path = "../oxidiviner-exponential-smoothing" }
oxidiviner-autoregressive = { version = "0.3.0", path = "../oxidiviner-autoregressive" }
oxidiviner-garch = { version = "0.3.0", path = "../oxidiviner-garch" } 